### ISSUE TITLE
Mesher option causes nothing to appear

### ISSUE THREAD

**Issue by z3t0** [maxogden/voxel-engine#111]
Using the line:
```javascript
mesher: voxel.meshers.culled,
```

causes the world to not appear. Just a white screen, no FPS indicator either.

**Comment by deathcap** [comment]
This mesher comes from https://github.com/maxogden/voxel/tree/master/meshers

Culled is very slow, are you sure its not just hung? I think the monotone mesher is broken, but I recall using culled before, it just was very laggy (but was required to workaround texture atlasing at the time). The default greedy mesher is much faster

**Comment by z3t0** [comment]
Okay that makes a lot of sense, when I posted that I had not taken much of a look into the code and was just trying some different settings mentioned on the README. This may be repetitive, but once again something super useful to mention on a wiki :smile:
